name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: echo -n ${{ secrets.KEYSTORE }} | base64 -d > release.keystore
      - run: ./gradlew bundleRelease
        env:
          ORG_GRADLE_PROJECT_storePassword: ${{ secrets.STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_keyPassword: ${{ secrets.KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_keyAlias: ${{ secrets.KEY_ALIAS }}
      - uses: actions/upload-artifact@v4
        with:
          name: aab
          path: app/build/outputs/bundle/release/app-release.aab
